version: "3.9"

services:
  classifier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5009:5009"
    environment:
      - FLASK_ENV=production
    restart: always
    command: ["python", "service.py"]